<p>Pøí¹tí øádné zasedání AS FEL se bude konat
<b>27.&nbsp;4.&nbsp;2012 od&nbsp;9:00</b>
v&nbsp;místnosti&nbsp;C4-80.</p>

<!--
<h4>Návrh programu:</h4>
<ol id='program'>
<li>Schválení programu
<li>Schválení zápisu 20. øádného zasedání
<li>Schálení Zprávy o hospodaøení ÈVUT FEL v roce 2011
<li>Schválení Rozpis dotace a pøíspìvku pro CVUT FEL v r. 2012
<li>Úprava smìrnic pro SZZ
<li>Pøíprava ankety na letní semestr
<li>Doplnìní Disciplinární komise (deadline 31.5.)
<li>Termín dal¹ího zasedání
<li>Rùzné<ol>
 <li>informace: výbìrové øízení na VK jazykù</li>
 <li>informace: kroky k vytvoøení (na dìkanátu)
 oddìlení pro zahranièní styky a vnìj¹í vztahy</li>
</ol></li>
</ol>-->

<h4>Související:</h4><ul>
<li><a href="https://felnet.feld.cvut.cz/infodek/SENAT/VEDENI/FUNKCNI%20OBDOBI%20AS%202010-13/">
Pøedkládané materiály</a></li>
<li>(Pou¾ijte heslo do sítì Novell v&nbsp;Dejvicích.)</li>
</ul>
<!--
<li><a href="http://www.fel.cvut.cz/aktuality/senat-zasedani.html">Pøenos ze zasedání</a></li>-->
<!--<li><a href="https://felnet.feld.cvut.cz/infodek/SENAT/PREDKLADANO/">-->

